export const generalItems = [
  {
    name: 'Rations (1 day)',
    price: '5 gp',
    type: 'general',
    is_service: false,
    description: "A day's worth of preserved food.",
    rarity: 'uncommon',
  },
  {
    name: 'Waterskin',
    price: '2 gp',
    type: 'general',
    is_service: false,
    description: 'A container for holding water.',
    rarity: 'uncommon',
  },
  {
    name: 'Torch',
    price: '1 sp',
    type: 'general',
    is_service: false,
    description: 'A simple torch for lighting.',
    rarity: 'uncommon',
  },
  {
    name: 'Bedroll',
    price: '1 gp',
    type: 'general',
    is_service: false,
    description: 'A roll of bedding for sleeping.',
    rarity: 'uncommon',
  },
  {
    name: 'Backpack',
    price: '2 gp',
    type: 'general',
    is_service: false,
    description: 'A bag for carrying items.',
    rarity: 'uncommon',
  },
  {
    name: 'Clothing (Common)',
    price: '5 gp',
    type: 'general',
    is_service: false,
    description: 'Common clothing for everyday wear.',
    rarity: 'uncommon',
  },
  {
    name: 'Sack',
    price: '1 cp',
    type: 'general',
    is_service: false,
    description: 'A simple sack for carrying items.',
    rarity: 'uncommon',
  },
  {
    name: 'Flint and Steel',
    price: '1 gp',
    type: 'general',
    is_service: false,
    description: 'Tools for starting a fire.',
    rarity: 'uncommon',
  },
  {
    name: 'Mess Kit',
    price: '2 sp',
    type: 'general',
    is_service: false,
    description: 'A kit for eating meals.',
    rarity: 'uncommon',
  },
  {
    name: 'Crowbar',
    price: '2 gp',
    type: 'general',
    is_service: false,
    description: 'A tool for prying open objects.',
    rarity: 'uncommon',
  },
  {
    name: 'Hammer',
    price: '1 gp',
    type: 'general',
    is_service: false,
    description: 'A tool for hammering nails.',
    rarity: 'uncommon',
  },
  {
    name: 'Tent',
    price: '10 gp',
    type: 'general',
    is_service: false,
    description: 'A shelter for camping.',
    rarity: 'uncommon',
  },
  {
    name: 'Mirror (Steel)',
    price: '5 gp',
    type: 'general',
    is_service: false,
    description: 'A small steel mirror.',
    rarity: 'uncommon',
  },
  {
    name: 'Piton (Iron)',
    price: '5 cp',
    type: 'general',
    is_service: false,
    description: 'A metal spike for climbing.',
    rarity: 'uncommon',
  },
  {
    name: 'Oil (Flask)',
    price: '1 sp',
    type: 'general',
    is_service: false,
    description: 'A flask of oil for lighting or lubrication.',
    rarity: 'uncommon',
  },
  {
    name: 'Tinderbox',
    price: '5 sp',
    type: 'general',
    is_service: false,
    description: 'A box containing tools for starting a fire.',
    rarity: 'uncommon',
  },
  {
    name: 'Whetstone',
    price: '1 cp',
    type: 'general',
    is_service: false,
    description: 'A stone for sharpening blades.',
    rarity: 'uncommon',
  },
  {
    name: 'Hempen Rope (50 feet)',
    price: '1 gp',
    type: 'general',
    is_service: false,
    description: 'A 50-foot length of hempen rope.',
    rarity: 'uncommon',
  },
  {
    name: 'Blanket',
    price: '5 sp',
    type: 'general',
    is_service: false,
    description: 'A warm blanket.',
    rarity: 'uncommon',
  },
  {
    name: 'Grappling Hook',
    price: '2 gp',
    type: 'general',
    is_service: false,
    description: 'A hook for climbing.',
    rarity: 'uncommon',
  },
  {
    name: 'Candles (x5)',
    price: '5 cp',
    type: 'general',
    is_service: false,
    description: 'A set of five candles.',
    rarity: 'uncommon',
  },
  {
    name: 'Tent (Large)',
    price: '20 gp',
    type: 'general',
    is_service: false,
    description: 'A large tent for camping.',
    rarity: 'uncommon',
  },
  {
    name: 'Ink (1 ounce bottle)',
    price: '10 gp',
    type: 'general',
    is_service: false,
    description: 'A bottle of ink for writing.',
    rarity: 'uncommon',
  },
  {
    name: 'Ink Pen',
    price: '2 cp',
    type: 'general',
    is_service: false,
    description: 'A pen for writing with ink.',
    rarity: 'uncommon',
  },
  {
    name: 'Paper (per sheet)',
    price: '2 sp',
    type: 'general',
    is_service: false,
    description: 'A sheet of paper for writing.',
    rarity: 'uncommon',
  },
  {
    name: "Healer's Kit",
    price: '5 gp',
    type: 'general',
    is_service: false,
    description: 'A kit for treating wounds.',
    rarity: 'uncommon',
  },
  {
    name: 'Antitoxin (vial)',
    price: '50 gp',
    type: 'general',
    is_service: false,
    description: 'A vial of antitoxin for treating poison.',
    rarity: 'uncommon',
  },
  {
    name: "Alchemist's Fire (flask)",
    price: '50 gp',
    type: 'general',
    is_service: false,
    description: 'A flask of alchemical fire.',
    rarity: 'uncommon',
  },
  {
    name: 'Block and Tackle',
    price: '1 gp',
    type: 'general',
    is_service: false,
    description: 'A set of pulleys for lifting heavy objects.',
    rarity: 'uncommon',
  },
  {
    name: 'Holy Water (flask)',
    price: '25 gp',
    type: 'general',
    is_service: false,
    description: 'A flask of holy water.',
    rarity: 'uncommon',
  },
  {
    name: 'Hourglass',
    price: '25 gp',
    type: 'general',
    is_service: false,
    description: 'A device for measuring time.',
    rarity: 'uncommon',
  },
  {
    name: 'Lantern',
    price: '5 gp',
    type: 'general',
    is_service: false,
    description: 'A lantern for lighting.',
    rarity: 'uncommon',
  },
  {
    name: 'Oil (per pint)',
    price: '1 sp',
    type: 'general',
    is_service: false,
    description: 'A pint of oil for lighting or lubrication.',
    rarity: 'uncommon',
  },
  {
    name: 'Parchment (per sheet)',
    price: '1 sp',
    type: 'general',
    is_service: false,
    description: 'A sheet of parchment for writing.',
    rarity: 'uncommon',
  },
  {
    name: 'Potion of Healing',
    price: '50 gp',
    type: 'general',
    is_service: false,
    description: 'A potion for healing wounds.',
    rarity: 'uncommon',
  },
  {
    name: 'Rope, silk (50 feet)',
    price: '10 gp',
    type: 'general',
    is_service: false,
    description: 'A 50-foot length of silk rope.',
    rarity: 'uncommon',
  },
  {
    name: 'Spyglass',
    price: '1,000 gp',
    type: 'general',
    is_service: false,
    description: 'A device for seeing distant objects.',
    rarity: 'uncommon',
  },
  {
    name: "Thieves' Tools",
    price: '25 gp',
    type: 'general',
    is_service: false,
    description: 'Tools for picking locks and disarming traps.',
    rarity: 'uncommon',
  },
  {
    name: 'Vial',
    price: '1 gp',
    type: 'general',
    is_service: false,
    description: 'A small container for holding liquids.',
    rarity: 'uncommon',
  },
  {
    name: 'Wagon',
    price: '35 gp',
    type: 'general',
    is_service: false,
    description: 'A vehicle for transporting goods.',
    rarity: 'uncommon',
  },
  {
    name: 'Bell',
    price: '1 gp',
    type: 'general',
    is_service: false,
    description: 'A small bell for making noise.',
    rarity: 'uncommon',
  },
  {
    name: 'Blanket, winter',
    price: '5 sp',
    type: 'general',
    is_service: false,
    description: 'A warm blanket for winter.',
    rarity: 'uncommon',
  },
  {
    name: 'Block and tackle',
    price: '1 gp',
    type: 'general',
    is_service: false,
    description: 'A set of pulleys for lifting heavy objects.',
    rarity: 'uncommon',
  },
  {
    name: 'Caltrops (bag of 20)',
    price: '1 gp',
    type: 'general',
    is_service: false,
    description: 'A bag of 20 caltrops for hindering movement.',
    rarity: 'uncommon',
  },
  {
    name: 'Canvas (per square yard)',
    price: '1 sp',
    type: 'general',
    is_service: false,
    description: 'A square yard of canvas for various uses.',
    rarity: 'uncommon',
  },
  {
    name: 'Chain (10 feet)',
    price: '5 gp',
    type: 'general',
    is_service: false,
    description: 'A 10-foot length of chain.',
    rarity: 'uncommon',
  },
  {
    name: 'Chalk (1 piece)',
    price: '1 cp',
    type: 'general',
    is_service: false,
    description: 'A piece of chalk for writing or drawing.',
    rarity: 'uncommon',
  },
  {
    name: "Climber's kit",
    price: '25 gp',
    type: 'general',
    is_service: false,
    description: 'A kit for climbing.',
    rarity: 'uncommon',
  },
  {
    name: 'Flask (empty)',
    price: '2 cp',
    type: 'general',
    is_service: false,
    description: 'An empty flask for holding liquids.',
    rarity: 'uncommon',
  },
  {
    name: 'Grappling hook',
    price: '2 gp',
    type: 'general',
    is_service: false,
    description: 'A hook for climbing.',
    rarity: 'uncommon',
  },
  {
    name: 'Hunting trap',
    price: '5 gp',
    type: 'general',
    is_service: false,
    description: 'A trap for catching animals.',
    rarity: 'uncommon',
  },
  {
    name: 'Iron spike',
    price: '1 cp',
    type: 'general',
    is_service: false,
    description: 'A metal spike for various uses.',
    rarity: 'uncommon',
  },
  {
    name: 'Ladder (10-foot)',
    price: '1 sp',
    type: 'general',
    is_service: false,
    description: 'A 10-foot ladder for climbing.',
    rarity: 'uncommon',
  },
  {
    name: 'Lock',
    price: '10 gp',
    type: 'general',
    is_service: false,
    description: 'A lock for securing items.',
    rarity: 'uncommon',
  },
  {
    name: 'Manacles',
    price: '2 gp',
    type: 'general',
    is_service: false,
    description: 'Restraints for securing a person.',
    rarity: 'uncommon',
  },
  {
    name: 'Mule',
    price: '8 gp',
    type: 'general',
    is_service: false,
    description: 'A pack animal for carrying goods.',
    rarity: 'uncommon',
  },
  {
    name: "Pick, miner's",
    price: '2 gp',
    type: 'general',
    is_service: false,
    description: 'A tool for mining.',
    rarity: 'uncommon',
  },
  {
    name: 'Pole (10-foot)',
    price: '5 cp',
    type: 'general',
    is_service: false,
    description: 'A 10-foot pole for various uses.',
    rarity: 'uncommon',
  },
  {
    name: 'Ram, portable',
    price: '4 gp',
    type: 'general',
    is_service: false,
    description: 'A portable ram for breaking doors.',
    rarity: 'uncommon',
  },
  {
    name: 'Saddle',
    price: '10 gp',
    type: 'general',
    is_service: false,
    description: 'A saddle for riding animals.',
    rarity: 'uncommon',
  },
  {
    name: 'Saddlebags',
    price: '4 gp',
    type: 'general',
    is_service: false,
    description: 'Bags for carrying items on a saddle.',
    rarity: 'uncommon',
  },
  {
    name: 'Sewing Needle',
    price: '5 sp',
    type: 'general',
    is_service: false,
    description: 'A needle for sewing.',
    rarity: 'uncommon',
  },
  {
    name: 'Signal Whistle',
    price: '5 cp',
    type: 'general',
    is_service: false,
    description: 'A whistle for signaling.',
    rarity: 'uncommon',
  },
  {
    name: 'Tent, Two-Person',
    price: '15 gp',
    type: 'general',
    is_service: false,
    description: 'A tent for two people.',
    rarity: 'uncommon',
  },
  {
    name: 'Torch (Bundle of 5)',
    price: '5 cp',
    type: 'general',
    is_service: false,
    description: 'A bundle of five torches.',
    rarity: 'uncommon',
  },
  {
    name: 'Vial, Ink or Potion',
    price: '1 gp',
    type: 'general',
    is_service: false,
    description: 'A vial for holding ink or potions.',
    rarity: 'uncommon',
  },
  {
    name: 'Wagon Wheel',
    price: '1 gp',
    type: 'general',
    is_service: false,
    description: 'A wheel for a wagon.',
    rarity: 'uncommon',
  },
  {
    name: 'Wagon, Large',
    price: '150 gp',
    type: 'general',
    is_service: false,
    description: 'A large wagon for transporting goods.',
    rarity: 'uncommon',
  },
  {
    name: 'Waterskin (Full)',
    price: '2 cp',
    type: 'general',
    is_service: false,
    description: 'A full waterskin for holding water.',
    rarity: 'uncommon',
  },
  {
    name: 'Whistle',
    price: '2 cp',
    type: 'general',
    is_service: false,
    description: 'A small whistle for signaling.',
    rarity: 'uncommon',
  },
  {
    name: 'Writing Ink (1 ounce)',
    price: '10 gp',
    type: 'general',
    is_service: false,
    description: 'An ounce of ink for writing.',
    rarity: 'uncommon',
  },
  {
    name: 'Animal Feed (per day)',
    price: '5 cp',
    type: 'general',
    is_service: false,
    description: 'Feed for animals for one day.',
    rarity: 'uncommon',
  },
  {
    name: 'Ball Bearings (Bag of 1,000)',
    price: '1 gp',
    type: 'general',
    is_service: false,
    description: 'A bag of 1,000 ball bearings.',
    rarity: 'uncommon',
  },
  {
    name: 'Barrel',
    price: '2 gp',
    type: 'general',
    is_service: false,
    description: 'A large container for storing liquids.',
    rarity: 'uncommon',
  },
  {
    name: 'Basket',
    price: '4 sp',
    type: 'general',
    is_service: false,
    description: 'A woven container for carrying items.',
    rarity: 'uncommon',
  },
  {
    name: 'Block and Tackle',
    price: '1 gp',
    type: 'general',
    is_service: false,
    description: 'A set of pulleys for lifting heavy objects.',
    rarity: 'uncommon',
  },
  {
    name: 'Bucket',
    price: '5 cp',
    type: 'general',
    is_service: false,
    description: 'A container for carrying liquids.',
    rarity: 'uncommon',
  },
  {
    name: 'Candle',
    price: '1 cp',
    type: 'general',
    is_service: false,
    description: 'A small candle for lighting.',
    rarity: 'uncommon',
  },
  {
    name: "Climber's Kit",
    price: '25 gp',
    type: 'general',
    is_service: false,
    description: 'A kit for climbing.',
    rarity: 'uncommon',
  },
  {
    name: 'Fishing Tackle',
    price: '1 gp',
    type: 'general',
    is_service: false,
    description: 'A set of tools for fishing.',
    rarity: 'uncommon',
  },
];

export const generalServices = [
  {
    name: 'Item Purchase',
    price: 'Varies',
    type: 'general',
    is_service: true,
    description:
      'Buy various goods and supplies such as food, clothing, tools, and other essentials.',
  },
  {
    name: 'Item Sale',
    price: 'Varies',
    type: 'general',
    is_service: true,
    description: 'Sell unwanted items or trade goods for coin or store credit.',
  },
  {
    name: 'Item Identification',
    price: '10 gp',
    type: 'general',
    is_service: true,
    description: 'Identify the properties or origins of unknown items.',
  },
  {
    name: 'Special Orders',
    price: 'Varies',
    type: 'general',
    is_service: true,
    description: 'Place special orders for hard-to-find or unique items.',
  },
  {
    name: 'Item Appraisal',
    price: '15 gp',
    type: 'general',
    is_service: true,
    description: 'Receive an expert appraisal of the value of items.',
  },
  {
    name: 'Item Repair',
    price: 'Varies',
    type: 'general',
    is_service: true,
    description: 'Repair damaged items or equipment.',
  },
  {
    name: 'Item Rental',
    price: 'Varies',
    type: 'general',
    is_service: true,
    description: 'Rent equipment or tools for temporary use.',
  },
  {
    name: 'Item Engraving',
    price: '5 gp',
    type: 'general',
    is_service: true,
    description: 'Add personalized engravings to items or gifts.',
  },
  {
    name: 'Item Cleaning',
    price: '5 gp',
    type: 'general',
    is_service: true,
    description: 'Professional cleaning and maintenance of items.',
  },
  {
    name: 'Item Consultation',
    price: '10 gp',
    type: 'general',
    is_service: true,
    description:
      'Consult with a shopkeeper for advice on item selection or use.',
  },
  {
    name: 'Item Exchange',
    price: 'Varies',
    type: 'general',
    is_service: true,
    description: 'Exchange items for store credit or trade with other patrons.',
  },
  {
    name: 'Item Donation',
    price: 'Varies',
    type: 'general',
    is_service: true,
    description: 'Donate items to the shop for charity or resale.',
  },
  {
    name: 'Item Recycling',
    price: 'Varies',
    type: 'general',
    is_service: true,
    description: 'Recycle old or broken items for materials or store credit.',
  },
  {
    name: 'Item Restoration',
    price: '30 gp',
    type: 'general',
    is_service: true,
    description:
      'Restore antique or damaged items to their original condition.',
  },
];
