export const armorItems = [
  {
    name: 'Leather Armor',
    price: '10 gp',
    rarity: 'common',
    is_service: false,
    type: 'armor',
    description: 'A basic armor made from toughened leather.',
  },
  {
    name: 'Chain Shirt',
    price: '50 gp',
    rarity: 'common',
    is_service: false,
    type: 'armor',
    description: 'A shirt made of interlocking metal rings.',
  },
  {
    name: 'Scale Mail',
    price: '50 gp',
    rarity: 'common',
    is_service: false,
    type: 'armor',
    description: 'Armor made of overlapping metal scales.',
  },
  {
    name: 'Breastplate',
    price: '400 gp',
    rarity: 'uncommon',
    is_service: false,
    type: 'armor',
    description: 'A solid metal plate that covers the torso.',
  },
  {
    name: 'Half Plate',
    price: '750 gp',
    rarity: 'uncommon',
    is_service: false,
    type: 'armor',
    description: 'Partial plate armor that offers good protection.',
  },
  {
    name: 'Ring Mail',
    price: '30 gp',
    rarity: 'common',
    is_service: false,
    type: 'armor',
    description: 'Armor made of metal rings sewn to a leather backing.',
  },
  {
    name: 'Chain Mail',
    price: '75 gp',
    rarity: 'common',
    is_service: false,
    type: 'armor',
    description: 'Armor made of interlocking metal rings.',
  },
  {
    name: 'Splint Armor',
    price: '200 gp',
    rarity: 'uncommon',
    is_service: false,
    type: 'armor',
    description: 'Armor made of narrow vertical strips of metal.',
  },
  {
    name: 'Plate Armor',
    price: '1500 gp',
    rarity: 'rare',
    is_service: false,
    type: 'armor',
    description: 'Full-body armor made of interlocking metal plates.',
  },
  {
    name: 'Shield',
    price: '10 gp',
    rarity: 'common',
    is_service: false,
    type: 'armor',
    description: 'A basic shield made of wood or metal.',
  },
  {
    name: 'Adamantine Armor',
    price: '5000 gp',
    rarity: 'legendary',
    is_service: false,
    type: 'armor',
    description: 'Armor made of the indestructible metal adamantine.',
  },
  {
    name: 'Dragon Scale Mail',
    price: '7500 gp',
    rarity: 'epic',
    is_service: false,
    type: 'armor',
    description: 'Armor made from the scales of a dragon.',
  },
  {
    name: 'Demon Armor',
    price: '10000 gp',
    rarity: 'epic',
    is_service: false,
    type: 'armor',
    description: 'Armor imbued with demonic power.',
  },
  {
    name: 'Dragonplate Armor',
    price: '25000 gp',
    rarity: 'epic',
    is_service: false,
    type: 'armor',
    description: 'Plate armor made from dragon scales.',
  },
  {
    name: 'Studded Leather Armor',
    price: '45 gp',
    rarity: 'common',
    is_service: false,
    type: 'armor',
    description: 'Leather armor reinforced with metal studs.',
  },
  {
    name: 'Elven Chain',
    price: '500 gp',
    rarity: 'rare',
    is_service: false,
    type: 'armor',
    description: 'A finely crafted chain shirt made by elves.',
  },
  {
    name: 'Mithral Armor',
    price: '5000 gp',
    rarity: 'rare',
    is_service: false,
    type: 'armor',
    description: 'Armor made from the lightweight metal mithral.',
  },
  {
    name: 'Plate Armor of Etherealness',
    price: '75000 gp',
    rarity: 'legendary',
    is_service: false,
    type: 'armor',
    description: 'Plate armor that allows the wearer to become ethereal.',
  },
  {
    name: 'Shield, +1',
    price: '1000 gp',
    rarity: 'uncommon',
    is_service: false,
    type: 'armor',
    description: 'A shield that provides a +1 bonus to AC.',
  },
  {
    name: 'Shield, +2',
    price: '4000 gp',
    rarity: 'rare',
    is_service: false,
    type: 'armor',
    description: 'A shield that provides a +2 bonus to AC.',
  },
  {
    name: 'Shield, +3',
    price: '9000 gp',
    rarity: 'rare',
    is_service: false,
    type: 'armor',
    description: 'A shield that provides a +3 bonus to AC.',
  },
  {
    name: 'Sentinel Shield',
    price: '2000 gp',
    rarity: 'uncommon',
    is_service: false,
    type: 'armor',
    description: 'A shield that grants advantage on initiative rolls.',
  },
  {
    name: 'Adamantine Shield',
    price: '5000 gp',
    rarity: 'legendary',
    is_service: false,
    type: 'armor',
    description: 'A shield made of the indestructible metal adamantine.',
  },
  {
    name: 'Animated Shield',
    price: '5000 gp',
    rarity: 'rare',
    is_service: false,
    type: 'armor',
    description: 'A shield that can animate and protect the wearer.',
  },
  {
    name: 'Demon Shield',
    price: '15000 gp',
    rarity: 'epic',
    is_service: false,
    type: 'armor',
    description: 'A shield imbued with demonic power.',
  },
  {
    name: 'Dragon Shield',
    price: '20000 gp',
    rarity: 'epic',
    is_service: false,
    type: 'armor',
    description: 'A shield made from dragon scales.',
  },
  {
    name: 'Cloak of Protection',
    price: '5000 gp',
    rarity: 'rare',
    is_service: false,
    type: 'armor',
    description: 'A cloak that grants a bonus to AC and saving throws.',
  },
  {
    name: 'Robe of the Archmagi',
    price: '30000 gp',
    rarity: 'epic',
    is_service: false,
    type: 'armor',
    description: 'A robe that grants powerful magical abilities.',
  },
  {
    name: 'Bracers of Defense',
    price: '4000 gp',
    rarity: 'uncommon',
    is_service: false,
    type: 'armor',
    description: 'Bracers that grant a bonus to AC when not wearing armor.',
  },
];

export const armorServices = [
  {
    name: 'Armor Repair',
    price: '20 gp',
    is_service: true,
    type: 'armor',
    description: 'Repair damaged armor to its original condition.',
  },
  {
    name: 'Armor Refitting',
    price: '30 gp',
    is_service: true,
    type: 'armor',
    description: "Refit armor to better fit the customer's body.",
  },
  {
    name: 'Armor Customization',
    price: '50 gp',
    is_service: true,
    type: 'armor',
    description: 'Customize armor with additional features or modifications.',
  },
  {
    name: 'Armor Enchantment',
    price: '100 gp',
    is_service: true,
    type: 'armor',
    description: 'Enchant armor with magical properties or enhancements.',
  },
  {
    name: 'Armor Appraisal',
    price: '15 gp',
    is_service: true,
    type: 'armor',
    description: 'Receive an expert appraisal of the value of armor.',
  },
  {
    name: 'Armor Maintenance Kit',
    price: '10 gp',
    is_service: true,
    type: 'armor',
    description: 'A kit containing tools and supplies for maintaining armor.',
  },
  {
    name: 'Armor Cleaning',
    price: '5 gp',
    is_service: true,
    type: 'armor',
    description: 'Professional cleaning and maintenance of armor.',
  },
  {
    name: 'Armor Display',
    price: '20 gp',
    is_service: true,
    type: 'armor',
    description: 'Display armor for sale or exhibition purposes.',
  },
  {
    name: 'Armor Rental',
    price: '30 gp',
    is_service: true,
    type: 'armor',
    description: 'Rent armor for temporary use or testing.',
  },
  {
    name: 'Armor Crafting Lessons',
    price: '40 gp',
    is_service: true,
    type: 'armor',
    description:
      'Learn the basics of armor crafting under the guidance of a skilled armorer.',
  },
  {
    name: 'Metal Plating',
    price: '50 gp',
    is_service: true,
    type: 'armor',
    description: 'Add metal plating to armor for enhanced protection.',
  },
  {
    name: 'Leatherworking',
    price: '25 gp',
    is_service: true,
    type: 'armor',
    description: 'Purchase custom leather armor or leatherworking supplies.',
  },
  {
    name: 'Armor Dyeing',
    price: '15 gp',
    is_service: true,
    type: 'armor',
    description: 'Dye armor to change its color or appearance.',
  },
  {
    name: 'Armor Consultation',
    price: '10 gp',
    is_service: true,
    type: 'armor',
    description:
      'Consult with an armor expert for advice on armor selection and care.',
  },
];
