export const magicItems = [
  {
    name: 'Potion of Healing',
    price: '50 gp',
    type: 'magic',
    rarity: 'common',
    description: 'A potion that heals 2d4 + 2 hit points.',
  },
  {
    name: 'Scroll of Cure Wounds',
    price: '25 gp',
    type: 'magic',
    rarity: 'common',
    description: 'A scroll that allows the casting of Cure Wounds spell.',
  },
  {
    name: 'Spell Scroll (Cantrip)',
    price: '25 gp',
    type: 'magic',
    rarity: 'common',
    description: 'A scroll that allows the casting of a cantrip.',
  },
  {
    name: 'Wand of Magic Missiles',
    price: '1000 gp',
    type: 'magic',
    rarity: 'uncommon',
    description: 'A wand that can cast Magic Missile spell.',
  },
  {
    name: 'Potion of Greater Healing',
    price: '150 gp',
    type: 'magic',
    rarity: 'uncommon',
    description: 'A potion that heals 4d4 + 4 hit points.',
  },
  {
    name: 'Scroll of Fireball',
    price: '500 gp',
    type: 'magic',
    rarity: 'uncommon',
    description: 'A scroll that allows the casting of Fireball spell.',
  },
  {
    name: 'Spell Scroll (2nd Level)',
    price: '200 gp',
    type: 'magic',
    rarity: 'uncommon',
    description: 'A scroll that allows the casting of a 2nd level spell.',
  },
  {
    name: 'Ring of Protection',
    price: '5000 gp',
    type: 'magic',
    rarity: 'rare',
    description: 'A ring that grants a +1 bonus to AC and saving throws.',
  },
  {
    name: 'Wand of Magic Detection',
    price: '500 gp',
    type: 'magic',
    rarity: 'rare',
    description: 'A wand that can detect magic.',
  },
  {
    name: 'Potion of Invisibility',
    price: '300 gp',
    type: 'magic',
    rarity: 'rare',
    description: 'A potion that grants invisibility for 1 hour.',
  },
  {
    name: 'Scroll of Resurrection',
    price: '1000 gp',
    type: 'magic',
    rarity: 'rare',
    description: 'A scroll that allows the casting of Resurrection spell.',
  },
  {
    name: 'Spell Scroll (5th Level)',
    price: '5000 gp',
    type: 'magic',
    rarity: 'rare',
    description: 'A scroll that allows the casting of a 5th level spell.',
  },
  {
    name: 'Staff of Power',
    price: '50000 gp',
    type: 'magic',
    rarity: 'legendary',
    description: 'A powerful staff with multiple magical abilities.',
  },
  {
    name: 'Robe of the Archmagi',
    price: '30000 gp',
    type: 'magic',
    rarity: 'legendary',
    description: 'A robe that grants various magical benefits to its wearer.',
  },
  {
    name: 'Amulet of Health',
    price: '10000 gp',
    type: 'magic',
    rarity: 'epic',
    description: "An amulet that increases the wearer's Constitution score.",
  },
  {
    name: 'Deck of Many Things',
    price: '50000 gp',
    type: 'magic',
    rarity: 'epic',
    description: 'A deck of cards with unpredictable magical effects.',
  },
  {
    name: 'Helm of Brilliance',
    price: '50000 gp',
    type: 'magic',
    rarity: 'epic',
    description: 'A helm that grants various magical abilities.',
  },
  {
    name: 'Manual of Bodily Health',
    price: '25000 gp',
    type: 'magic',
    rarity: 'epic',
    description: "A manual that increases the reader's Constitution score.",
  },
  {
    name: 'Tome of Clear Thought',
    price: '25000 gp',
    type: 'magic',
    rarity: 'epic',
    description: "A tome that increases the reader's Intelligence score.",
  },
  {
    name: 'Apparatus of Kwalish',
    price: '50000 gp',
    type: 'magic',
    rarity: 'epic',
    description: 'A magical vehicle with various abilities.',
  },
  {
    name: 'Potion of Climbing',
    price: '180 gp',
    type: 'magic',
    rarity: 'uncommon',
    description: 'A potion that grants climbing speed equal to walking speed.',
  },
  {
    name: 'Potion of Diminution',
    price: '500 gp',
    type: 'magic',
    rarity: 'rare',
    description: "A potion that reduces the drinker's size.",
  },
  {
    name: 'Potion of Growth',
    price: '500 gp',
    type: 'magic',
    rarity: 'rare',
    description: "A potion that increases the drinker's size.",
  },
  {
    name: 'Potion of Gaseous Form',
    price: '500 gp',
    type: 'magic',
    rarity: 'rare',
    description: 'A potion that turns the drinker into a gaseous form.',
  },
  {
    name: 'Potion of Hill Giant Strength',
    price: '180 gp',
    type: 'magic',
    rarity: 'uncommon',
    description: 'A potion that grants the strength of a hill giant.',
  },
  {
    name: 'Potion of Superior Healing',
    price: '450 gp',
    type: 'magic',
    rarity: 'rare',
    description: 'A potion that heals 8d4 + 8 hit points.',
  },
  {
    name: 'Spell Scroll (3rd Level)',
    price: '400 gp',
    type: 'magic',
    rarity: 'uncommon',
    description: 'A scroll that allows the casting of a 3rd level spell.',
  },
  {
    name: 'Spell Scroll (4th Level)',
    price: '800 gp',
    type: 'magic',
    rarity: 'rare',
    description: 'A scroll that allows the casting of a 4th level spell.',
  },
  {
    name: 'Spell Scroll (6th Level)',
    price: '10000 gp',
    type: 'magic',
    rarity: 'epic',
    description: 'A scroll that allows the casting of a 6th level spell.',
  },
  {
    name: 'Wand of Polymorph',
    price: '10000 gp',
    type: 'magic',
    rarity: 'rare',
    description: 'A wand that can cast Polymorph spell.',
  },
  {
    name: 'Wand of the War Mage, +1',
    price: '2500 gp',
    type: 'magic',
    rarity: 'rare',
    description: 'A wand that grants a +1 bonus to spell attack rolls.',
  },
  {
    name: 'Wand of the War Mage, +2',
    price: '5000 gp',
    type: 'magic',
    rarity: 'rare',
    description: 'A wand that grants a +2 bonus to spell attack rolls.',
  },
  {
    name: 'Wand of the War Mage, +3',
    price: '7500 gp',
    type: 'magic',
    rarity: 'rare',
    description: 'A wand that grants a +3 bonus to spell attack rolls.',
  },
  {
    name: 'Staff of Fire',
    price: '20000 gp',
    type: 'magic',
    rarity: 'epic',
    description: 'A staff that can cast various fire spells.',
  },
  {
    name: 'Staff of Healing',
    price: '20000 gp',
    type: 'magic',
    rarity: 'epic',
    description: 'A staff that can cast various healing spells.',
  },
  {
    name: 'Staff of Swarming Insects',
    price: '20000 gp',
    type: 'magic',
    rarity: 'epic',
    description: 'A staff that can summon swarming insects.',
  },
  {
    name: 'Rod of Absorption',
    price: '50000 gp',
    type: 'magic',
    rarity: 'legendary',
    description: 'A rod that can absorb spells cast at the wielder.',
  },
  {
    name: 'Rod of the Pact Keeper, +1',
    price: '2500 gp',
    type: 'magic',
    rarity: 'rare',
    description:
      'A rod that grants a +1 bonus to spell attack rolls and saving throw DCs.',
  },
  {
    name: 'Rod of the Pact Keeper, +2',
    price: '5000 gp',
    type: 'magic',
    rarity: 'rare',
    description:
      'A rod that grants a +2 bonus to spell attack rolls and saving throw DCs.',
  },
  {
    name: 'Rod of the Pact Keeper, +3',
    price: '7500 gp',
    type: 'magic',
    rarity: 'rare',
    description:
      'A rod that grants a +3 bonus to spell attack rolls and saving throw DCs.',
  },
  {
    name: 'Scroll of Detect Magic',
    price: '25 gp',
    type: 'magic',
    rarity: 'common',
    description: 'A scroll that allows the casting of Detect Magic spell.',
  },
  {
    name: 'Scroll of Mage Armor',
    price: '25 gp',
    type: 'magic',
    rarity: 'common',
    description: 'A scroll that allows the casting of Mage Armor spell.',
  },
  {
    name: 'Scroll of Shield',
    price: '25 gp',
    type: 'magic',
    rarity: 'common',
    description: 'A scroll that allows the casting of Shield spell.',
  },
  {
    name: 'Scroll of Thunderwave',
    price: '25 gp',
    type: 'magic',
    rarity: 'common',
    description: 'A scroll that allows the casting of Thunderwave spell.',
  },
  {
    name: 'Potion of Animal Friendship',
    price: '100 gp',
    type: 'magic',
    rarity: 'uncommon',
    description:
      'A potion that allows the drinker to cast Animal Friendship spell.',
  },
  {
    name: 'Potion of Clairvoyance',
    price: '250 gp',
    type: 'magic',
    rarity: 'rare',
    description: 'A potion that allows the drinker to cast Clairvoyance spell.',
  },
  {
    name: 'Potion of Climbing',
    price: '180 gp',
    type: 'magic',
    rarity: 'uncommon',
    description: 'A potion that grants climbing speed equal to walking speed.',
  },
  {
    name: 'Potion of Cloud Giant Strength',
    price: '180 gp',
    type: 'magic',
    rarity: 'uncommon',
    description: 'A potion that grants the strength of a cloud giant.',
  },
  {
    name: 'Potion of Diminution',
    price: '500 gp',
    type: 'magic',
    rarity: 'rare',
    description: "A potion that reduces the drinker's size.",
  },
  {
    name: 'Potion of Flying',
    price: '500 gp',
    type: 'magic',
    rarity: 'rare',
    description: 'A potion that grants the ability to fly.',
  },
  {
    name: 'Potion of Gaseous Form',
    price: '500 gp',
    type: 'magic',
    rarity: 'rare',
    description: 'A potion that turns the drinker into a gaseous form.',
  },
  {
    name: 'Potion of Giant Strength (Fire)',
    price: '180 gp',
    type: 'magic',
    rarity: 'uncommon',
    description: 'A potion that grants the strength of a fire giant.',
  },
  {
    name: 'Potion of Greater Healing',
    price: '150 gp',
    type: 'magic',
    rarity: 'uncommon',
    description: 'A potion that heals 4d4 + 4 hit points.',
  },
  {
    name: 'Potion of Growth',
    price: '500 gp',
    type: 'magic',
    rarity: 'rare',
    description: "A potion that increases the drinker's size.",
  },
  {
    name: 'Potion of Healing',
    price: '50 gp',
    type: 'magic',
    rarity: 'common',
    description: 'A potion that heals 2d4 + 2 hit points.',
  },
  {
    name: 'Potion of Heroism',
    price: '180 gp',
    type: 'magic',
    rarity: 'uncommon',
    description:
      'A potion that grants temporary hit points and the effects of the Bless spell.',
  },
  {
    name: 'Potion of Invisibility',
    price: '300 gp',
    type: 'magic',
    rarity: 'rare',
    description: 'A potion that grants invisibility for 1 hour.',
  },
  {
    name: 'Potion of Longevity',
    price: '2500 gp',
    type: 'magic',
    rarity: 'rare',
    description: "A potion that reduces the drinker's age by 1d6 + 6 years.",
  },
  {
    name: 'Potion of Mind Reading',
    price: '180 gp',
    type: 'magic',
    rarity: 'uncommon',
    description:
      'A potion that allows the drinker to cast Detect Thoughts spell.',
  },
  {
    name: 'Potion of Speed',
    price: '500 gp',
    type: 'magic',
    rarity: 'rare',
    description: 'A potion that grants the effects of the Haste spell.',
  },
  {
    name: 'Scroll of Acid Arrow',
    price: '150 gp',
    type: 'magic',
    rarity: 'uncommon',
    description: 'A scroll that allows the casting of Acid Arrow spell.',
  },
  {
    name: 'Scroll of Darkness',
    price: '150 gp',
    type: 'magic',
    rarity: 'uncommon',
    description: 'A scroll that allows the casting of Darkness spell.',
  },
  {
    name: 'Scroll of Death Ward',
    price: '250 gp',
    type: 'magic',
    rarity: 'rare',
    description: 'A scroll that allows the casting of Death Ward spell.',
  },
  {
    name: 'Scroll of Dimension Door',
    price: '250 gp',
    type: 'magic',
    rarity: 'rare',
    description: 'A scroll that allows the casting of Dimension Door spell.',
  },
  {
    name: 'Scroll of Dispel Magic',
    price: '150 gp',
    type: 'magic',
    rarity: 'uncommon',
    description: 'A scroll that allows the casting of Dispel Magic spell.',
  },
  {
    name: 'Scroll of Dominate Person',
    price: '250 gp',
    type: 'magic',
    rarity: 'rare',
    description: 'A scroll that allows the casting of Dominate Person spell.',
  },
  {
    name: 'Scroll of Enlarge/Reduce',
    price: '150 gp',
    type: 'magic',
    rarity: 'uncommon',
    description: 'A scroll that allows the casting of Enlarge/Reduce spell.',
  },
  {
    name: 'Scroll of Feather Fall',
    price: '50 gp',
    type: 'magic',
    rarity: 'common',
    description: 'A scroll that allows the casting of Feather Fall spell.',
  },
  {
    name: 'Scroll of Fireball',
    price: '500 gp',
    type: 'magic',
    rarity: 'rare',
    description: 'A scroll that allows the casting of Fireball spell.',
  },
  {
    name: 'Scroll of Fly',
    price: '250 gp',
    type: 'magic',
    rarity: 'rare',
    description: 'A scroll that allows the casting of Fly spell.',
  },
  {
    name: 'Scroll of Haste',
    price: '500 gp',
    type: 'magic',
    rarity: 'rare',
    description: 'A scroll that allows the casting of Haste spell.',
  },
  {
    name: 'Scroll of Hold Person',
    price: '150 gp',
    type: 'magic',
    rarity: 'uncommon',
    description: 'A scroll that allows the casting of Hold Person spell.',
  },
  {
    name: 'Scroll of Invisibility',
    price: '150 gp',
    type: 'magic',
    rarity: 'uncommon',
    description: 'A scroll that allows the casting of Invisibility spell.',
  },
  {
    name: 'Scroll of Lightning Bolt',
    price: '250 gp',
    type: 'magic',
    rarity: 'rare',
    description: 'A scroll that allows the casting of Lightning Bolt spell.',
  },
  {
    name: 'Scroll of Mage Armor',
    price: '25 gp',
    type: 'magic',
    rarity: 'common',
    description: 'A scroll that allows the casting of Mage Armor spell.',
  },
  {
    name: 'Scroll of Magic Missile',
    price: '50 gp',
    type: 'magic',
    rarity: 'common',
    description: 'A scroll that allows the casting of Magic Missile spell.',
  },
  {
    name: 'Scroll of Misty Step',
    price: '150 gp',
    type: 'magic',
    rarity: 'uncommon',
    description: 'A scroll that allows the casting of Misty Step spell.',
  },
  {
    name: 'Scroll of Polymorph',
    price: '250 gp',
    type: 'magic',
    rarity: 'rare',
    description: 'A scroll that allows the casting of Polymorph spell.',
  },
  {
    name: 'Scroll of Protection from Energy',
    price: '250 gp',
    type: 'magic',
    rarity: 'rare',
    description:
      'A scroll that allows the casting of Protection from Energy spell.',
  },
  {
    name: 'Scroll of Revivify',
    price: '250 gp',
    type: 'magic',
    rarity: 'rare',
    description: 'A scroll that allows the casting of Revivify spell.',
  },
];

export const magicServices = [
  {
    name: 'Spell Scroll Scribing',
    price: '50 gp',
    type: 'magic',
    is_service: true,
    description: "Scribe a spell scroll with a spell of the customer's choice.",
  },
  {
    name: 'Potion Brewing',
    price: '100 gp',
    type: 'magic',
    is_service: true,
    description: 'Craft a magical potion with a specific effect.',
  },
  {
    name: 'Enchantment Services',
    price: 'Varies',
    type: 'magic',
    is_service: true,
    description: 'Enchant items with magical properties or enhancements.',
  },
  {
    name: 'Divination Services',
    price: '50 gp',
    type: 'magic',
    is_service: true,
    description:
      'Request divination services for insight into the future or otherworldly knowledge.',
  },
  {
    name: 'Spellcasting Services',
    price: 'Varies',
    type: 'magic',
    is_service: true,
    description:
      'Hire a spellcaster to cast spells or rituals for specific purposes.',
  },
  {
    name: 'Magical Item Identification',
    price: '20 gp',
    type: 'magic',
    is_service: true,
    description: 'Identify magical properties or abilities of items.',
  },
  {
    name: 'Magical Consultation',
    price: '25 gp',
    type: 'magic',
    is_service: true,
    description: 'Consult with a magic expert for advice on magical matters.',
  },
  {
    name: 'Wand Crafting',
    price: '200 gp',
    type: 'magic',
    is_service: true,
    description: 'Craft a custom magical wand with specific abilities.',
  },
  {
    name: 'Scroll Restoration',
    price: '30 gp',
    type: 'magic',
    is_service: true,
    description: 'Restore damaged or faded spell scrolls to usable condition.',
  },
  {
    name: 'Magical Research',
    price: 'Varies',
    type: 'magic',
    is_service: true,
    description:
      'Commission research into specific magical topics or phenomena.',
  },
  {
    name: 'Arcane Tattooing',
    price: '100 gp',
    type: 'magic',
    is_service: true,
    description:
      'Receive a magical tattoo imbued with magical properties or abilities.',
  },
  {
    name: 'Magical Warding',
    price: '50 gp',
    type: 'magic',
    is_service: true,
    description:
      'Have magical wards or protections placed on a location or object.',
  },
  {
    name: 'Planar Travel Services',
    price: '500 gp',
    type: 'magic',
    is_service: true,
    description: 'Arrange for travel to other planes of existence.',
  },
  {
    name: 'Alchemy Supplies',
    price: 'Varies',
    type: 'magic',
    is_service: true,
    description:
      'Purchase rare and exotic alchemical ingredients for potion brewing.',
  },
  {
    name: 'Spellbook Transcription',
    price: '30 gp',
    type: 'magic',
    is_service: true,
    description: 'Transcribe spells from one spellbook to another.',
  },
];
