export const miscItems = [
  {
    name: 'Loaf of Bread',
    type: 'misc',
    price: '2 cp',
    rarity: 'common',
  },
  {
    name: 'Wedge of Cheese',
    type: 'misc',
    price: '1 sp',
    rarity: 'common',
  },
  {
    name: 'Apple',
    type: 'misc',
    price: '5 cp',
    rarity: 'common',
  },
  {
    name: 'Pear',
    type: 'misc',
    price: '5 cp',
    rarity: 'common',
  },
  {
    name: 'Pint of Ale',
    type: 'misc',
    price: '4 cp',
    rarity: 'common',
  },
  {
    name: 'Bottle of Wine',
    type: 'misc',
    price: '2 sp',
    rarity: 'common',
  },
  {
    name: 'Sack of Potatoes',
    type: 'misc',
    price: '3 sp',
    rarity: 'common',
  },
  {
    name: 'Barrel of Ale',
    type: 'misc',
    price: '1 gp',
    rarity: 'common',
  },
  {
    name: 'Wheel of Cheese',
    type: 'misc',
    price: '5 gp',
    rarity: 'common',
  },
  {
    name: 'Bunch of Grapes',
    type: 'misc',
    price: '1 sp',
    rarity: 'common',
  },
  {
    name: 'Pint of Mead',
    type: 'misc',
    price: '5 cp',
    rarity: 'common',
  },
  {
    name: 'Bottle of Whiskey',
    type: 'misc',
    price: '2 gp',
    rarity: 'uncommon',
  },
  {
    name: 'Sack of Flour',
    type: 'misc',
    price: '1 gp',
    rarity: 'common',
  },
  {
    name: 'Bottle of Fine Wine',
    type: 'misc',
    price: '10 gp',
    rarity: 'uncommon',
  },
  {
    name: 'Bottle of Champagne',
    type: 'misc',
    price: '20 gp',
    rarity: 'uncommon',
  },
  {
    name: 'Large Ham',
    type: 'misc',
    price: '3 gp',
    rarity: 'common',
  },
  {
    name: 'Whole Roasted Chicken',
    type: 'misc',
    price: '2 gp',
    rarity: 'common',
  },
  {
    name: 'Box of Tea Leaves',
    type: 'misc',
    price: '5 sp',
    rarity: 'common',
  },
  {
    name: 'Keg of Rum',
    type: 'misc',
    price: '50 gp',
    rarity: 'uncommon',
  },
  {
    name: 'Bottle of Absinthe',
    type: 'misc',
    price: '100 gp',
    rarity: 'rare',
  },
  {
    name: 'Bread Roll',
    type: 'misc',
    price: '1 cp',
    rarity: 'common',
  },
  {
    name: 'Block of Cheddar Cheese',
    type: 'misc',
    price: '5 sp',
    rarity: 'common',
  },
  {
    name: 'Orange',
    type: 'misc',
    price: '5 cp',
    rarity: 'common',
  },
  {
    name: 'Banana',
    type: 'misc',
    price: '5 cp',
    rarity: 'common',
  },
  {
    name: 'Tankard of Beer',
    type: 'misc',
    price: '3 cp',
    rarity: 'common',
  },
  {
    name: 'Bottle of Ale',
    type: 'misc',
    price: '2 sp',
    rarity: 'common',
  },
  {
    name: 'Bag of Rice',
    type: 'misc',
    price: '2 sp',
    rarity: 'common',
  },
  {
    name: 'Bottle of Cider',
    type: 'misc',
    price: '4 sp',
    rarity: 'common',
  },
  {
    name: 'Wheel of Gouda Cheese',
    type: 'misc',
    price: '7 gp',
    rarity: 'common',
  },
  {
    name: 'Bundle of Carrots',
    type: 'misc',
    price: '5 cp',
    rarity: 'common',
  },
  {
    name: 'Mug of Mead',
    type: 'misc',
    price: '4 cp',
    rarity: 'common',
  },
  {
    name: 'Flask of Whiskey',
    type: 'misc',
    price: '3 sp',
    rarity: 'uncommon',
  },
  {
    name: 'Bottle of Brandy',
    type: 'misc',
    price: '4 gp',
    rarity: 'uncommon',
  },
  {
    name: 'Sack of Sugar',
    type: 'misc',
    price: '1 gp',
    rarity: 'common',
  },
  {
    name: 'Barrel of Lager',
    type: 'misc',
    price: '3 gp',
    rarity: 'uncommon',
  },
  {
    name: 'Block of Swiss Cheese',
    type: 'misc',
    price: '8 gp',
    rarity: 'common',
  },
  {
    name: 'Jar of Pickles',
    type: 'misc',
    price: '1 sp',
    rarity: 'common',
  },
  {
    name: 'Bottle of Tequila',
    type: 'misc',
    price: '5 gp',
    rarity: 'uncommon',
  },
  {
    name: 'Pound of Bacon',
    type: 'misc',
    price: '3 sp',
    rarity: 'common',
  },
  {
    name: 'Roast Leg of Lamb',
    type: 'misc',
    price: '5 gp',
    rarity: 'common',
  },
  {
    name: 'Jar of Honey',
    type: 'misc',
    price: '2 sp',
    rarity: 'common',
  },
  {
    name: 'Cask of Ale',
    type: 'misc',
    price: '6 gp',
    rarity: 'uncommon',
  },
  {
    name: 'Barrel of Wine',
    type: 'misc',
    price: '8 gp',
    rarity: 'uncommon',
  },
  {
    name: 'Wheel of Brie Cheese',
    type: 'misc',
    price: '10 gp',
    rarity: 'common',
  },
  {
    name: 'Bundle of Asparagus',
    type: 'misc',
    price: '2 sp',
    rarity: 'common',
  },
  {
    name: 'Crate of Oranges',
    type: 'misc',
    price: '3 gp',
    rarity: 'common',
  },
  {
    name: 'Bottle of Vodka',
    type: 'misc',
    price: '6 gp',
    rarity: 'uncommon',
  },
  {
    name: 'Box of Cigars',
    type: 'misc',
    price: '5 gp',
    rarity: 'uncommon',
  },
  {
    name: 'Loaf of Rye Bread',
    type: 'misc',
    price: '3 cp',
    rarity: 'common',
  },
  {
    name: 'Block of Blue Cheese',
    type: 'misc',
    price: '12 gp',
    rarity: 'common',
  },
  {
    name: 'Bundle of Grapes',
    type: 'misc',
    price: '4 sp',
    rarity: 'common',
  },
  {
    name: 'Bottle of Vermouth',
    type: 'misc',
    price: '8 gp',
    rarity: 'uncommon',
  },
  {
    name: 'Can of Soda',
    type: 'misc',
    price: '2 cp',
    rarity: 'common',
  },
  {
    name: 'Flask of Cognac',
    type: 'misc',
    price: '7 gp',
    rarity: 'uncommon',
  },
  {
    name: 'Bottle of Rum',
    type: 'misc',
    price: '5 gp',
    rarity: 'uncommon',
  },
  {
    name: 'Jar of Olives',
    type: 'misc',
    price: '1 gp',
    rarity: 'common',
  },
  {
    name: 'Bucket of Fried Chicken',
    type: 'misc',
    price: '4 gp',
    rarity: 'common',
  },
  {
    name: 'Bundle of Bananas',
    type: 'misc',
    price: '3 cp',
    rarity: 'common',
  },
  {
    name: 'Bottle of Sake',
    type: 'misc',
    price: '10 gp',
    rarity: 'uncommon',
  },
  {
    name: 'Bag of Coffee Beans',
    type: 'misc',
    price: '2 gp',
    rarity: 'common',
  },
  {
    name: 'Crate of Apples',
    type: 'misc',
    price: '4 gp',
    rarity: 'common',
  },
  {
    name: 'Barrel of Brandy',
    type: 'misc',
    price: '12 gp',
    rarity: 'uncommon',
  },
  {
    name: 'Jar of Raspberry Jam',
    type: 'misc',
    price: '1 gp',
    rarity: 'common',
  },
  {
    name: 'Box of Chocolates',
    type: 'misc',
    price: '5 gp',
    rarity: 'common',
  },
  {
    name: 'Wheel of Edam Cheese',
    type: 'misc',
    price: '15 gp',
    rarity: 'common',
  },
  {
    name: 'Bundle of Leeks',
    type: 'misc',
    price: '2 sp',
    rarity: 'common',
  },
  {
    name: 'Crate of Lemons',
    type: 'misc',
    price: '4 gp',
    rarity: 'common',
  },
  {
    name: 'Bottle of Mulled Wine',
    type: 'misc',
    price: '6 gp',
    rarity: 'uncommon',
  },
  {
    name: 'Can of Beer',
    type: 'misc',
    price: '2 cp',
    rarity: 'common',
  },
  {
    name: 'Flask of Tequila',
    type: 'misc',
    price: '8 gp',
    rarity: 'uncommon',
  },
  {
    name: 'Bottle of Absinthe',
    type: 'misc',
    price: '15 gp',
    rarity: 'rare',
  },
  {
    name: 'Jar of Maple Syrup',
    type: 'misc',
    price: '2 gp',
    rarity: 'common',
  },
  {
    name: 'Sack of Oats',
    type: 'misc',
    price: '1 gp',
    rarity: 'common',
  },
  {
    name: 'Barrel of Stout',
    type: 'misc',
    price: '10 gp',
    rarity: 'uncommon',
  },
  {
    name: 'Block of Gruyere Cheese',
    type: 'misc',
    price: '20 gp',
    rarity: 'common',
  },
  {
    name: 'Bundle of Broccoli',
    type: 'misc',
    price: '3 sp',
    rarity: 'common',
  },
  {
    name: 'Crate of Strawberries',
    type: 'misc',
    price: '5 gp',
    rarity: 'common',
  },
  {
    name: 'Bottle of Gin',
    type: 'misc',
    price: '8 gp',
    rarity: 'uncommon',
  },
  {
    name: 'Box of Fine Cigars',
    type: 'misc',
    price: '10 gp',
    rarity: 'uncommon',
  },
  {
    name: 'Loaf of Sourdough Bread',
    type: 'misc',
    price: '4 cp',
    rarity: 'common',
  },
  {
    name: 'Block of Gorgonzola Cheese',
    type: 'misc',
    price: '25 gp',
    rarity: 'common',
  },
  {
    name: 'Bundle of Blueberries',
    type: 'misc',
    price: '4 sp',
    rarity: 'common',
  },
  {
    name: 'Bottle of Whiskey',
    type: 'misc',
    price: '12 gp',
    rarity: 'uncommon',
  },
  {
    name: 'Cask of Wine',
    type: 'misc',
    price: '15 gp',
    rarity: 'uncommon',
  },
  {
    name: 'Wheel of Roquefort Cheese',
    type: 'misc',
    price: '30 gp',
    rarity: 'common',
  },
  {
    name: 'Bundle of Cabbage',
    type: 'misc',
    price: '3 sp',
    rarity: 'common',
  },
  {
    name: 'Crate of Watermelons',
    type: 'misc',
    price: '6 gp',
    rarity: 'common',
  },
  {
    name: 'Bottle of Bourbon',
    type: 'misc',
    price: '10 gp',
    rarity: 'uncommon',
  },
  {
    name: 'Jar of Pickled Onions',
    type: 'misc',
    price: '1 gp',
    rarity: 'common',
  },
  {
    name: 'Bucket of Fried Fish',
    type: 'misc',
    price: '5 gp',
    rarity: 'common',
  },
  {
    name: 'Bundle of Strawberries',
    type: 'misc',
    price: '2 sp',
    rarity: 'common',
  },
  {
    name: 'Crate of Peaches',
    type: 'misc',
    price: '4 gp',
    rarity: 'common',
  },
  {
    name: 'Bottle of Rum',
    type: 'misc',
    price: '8 gp',
    rarity: 'uncommon',
  },
  {
    name: 'Barrel of Ale',
    type: 'misc',
    price: '10 gp',
    rarity: 'uncommon',
  },
  {
    name: 'Wheel of Camembert Cheese',
    type: 'misc',
    price: '35 gp',
    rarity: 'common',
  },
  {
    name: 'Bundle of Cauliflower',
    type: 'misc',
    price: '4 sp',
    rarity: 'common',
  },
  {
    name: 'Crate of Kiwis',
    type: 'misc',
    price: '7 gp',
    rarity: 'common',
  },
];

export const miscServices = [
  {
    name: 'Catering',
    type: 'misc',
    price: '50 gp',
    is_service: true,
    description: 'Provide food and drink for events or parties.',
  },
  {
    name: 'Meal Preparation',
    type: 'misc',
    price: '10 gp',
    is_service: true,
    description: 'Preparation of meals for special occasions.',
  },
  {
    name: 'Brewing Classes',
    type: 'misc',
    price: '20 gp',
    is_service: true,
    description: 'Learn the art of brewing beer or mead.',
  },
  {
    name: 'Wine Tasting',
    type: 'misc',
    price: '15 gp',
    is_service: true,
    description: 'Guided tasting sessions of various wines.',
  },
  {
    name: 'Cooking Lessons',
    type: 'misc',
    price: '15 gp',
    is_service: true,
    description: 'Learn to cook a variety of dishes.',
  },
  {
    name: 'Bartending Workshops',
    type: 'misc',
    price: '20 gp',
    is_service: true,
    description: 'Learn to mix and serve drinks like a professional bartender.',
  },
  {
    name: 'Cheese Pairing Classes',
    type: 'misc',
    price: '25 gp',
    is_service: true,
    description: 'Discover the art of pairing cheese with wine or beer.',
  },
  {
    name: 'Jam Making Workshops',
    type: 'misc',
    price: '15 gp',
    is_service: true,
    description: 'Learn to make your own jams and preserves.',
  },
  {
    name: 'Chocolate Tasting',
    type: 'misc',
    price: '10 gp',
    is_service: true,
    description: 'Indulge in a tasting experience of fine chocolates.',
  },
  {
    name: 'Cake Decorating Classes',
    type: 'misc',
    price: '20 gp',
    is_service: true,
    description: 'Learn the art of decorating cakes with frosting and fondant.',
  },
  {
    name: 'Tea Ceremony',
    type: 'misc',
    price: '10 gp',
    is_service: true,
    description: 'Participate in a traditional tea ceremony.',
  },
  {
    name: 'Wine Making Workshops',
    type: 'misc',
    price: '30 gp',
    is_service: true,
    description: 'Learn to make your own wine from start to finish.',
  },
  {
    name: 'Baking Classes',
    type: 'misc',
    price: '15 gp',
    is_service: true,
    description: 'Master the art of baking bread, pastries, and desserts.',
  },
  {
    name: 'Cocktail Masterclass',
    type: 'misc',
    price: '25 gp',
    is_service: true,
    description: 'Learn to craft classic and signature cocktails.',
  },
  {
    name: 'Gourmet Food Tours',
    type: 'misc',
    price: '30 gp',
    is_service: true,
    description: 'Guided tours to discover local culinary delights.',
  },
];
